name: TEST2
on:
  push:
    # branches: [ master ]
    paths:
      - '.github/workflows/**'

jobs:
  stuff:
    name: DoStuff
    runs-on: ubuntu-latest
    env:
      LOG_URL: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          previews: flash
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: deployment } = await github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              auto_merge: false,
              environment: 'appengine-staging',
              required_contexts: [], 
            });
            await github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.id,
              state: 'in_progress',
              target_url: process.env.LOG_URL,
              environment_url: 'https://github.com/advayDev1/actions-sandbox-ignore/',
            });
            return deployment.id;
      - run: echo a
      - uses: actions/github-script@v2
        if: always()
        with:
          previews: flash
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.id,
              state: '${{job.status}}' === 'success' ? 'success' : 'failure',
            });
            return deployment.id;
