name: TEST2
on:
  push:
    # branches: [ master ]
    paths:
      - '.github/workflows/**'

jobs:
  stuff:
    name: DoStuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: deployment } = await github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              auto_merge: false,
              environment: 'appengine-staging',
              required_contexts: [], 
            });
            await octokit.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.id,
              state: 'in_progress',
              target_url: 'https://github.com/advayDev1/actions-sandbox-ignore/edit/master/.github/workflows/dep.yaml',
              environment_url: 'https://github.com/advayDev1/actions-sandbox-ignore/',
            });
            return deployment.id;
