name: EnforceSquash
on:
  pull_request:
    branches: [ master ]

jobs:
  require_squash:
    name: Pull request must be squashed to single commit
    runs-on: ubuntu-latest
    env:
      LOG_URL: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: 'git show origin/${{github.base_ref}}'
      - run: 'git show origin/${{github.head_ref}}'
      - run: 'git rev-list --count origin/${{github.base_ref}}..origin/${{github.head_ref}} | wc -l'
      - run: echo DONE
        
